services:

  app:
    image: portainer/portainer-ce:2.21.3
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    networks:
      frontend:
      vpn:

networks:
  frontend:
  vpn:

volumes:
  data:
